version: '3'

volumes:
  static:
  database:

services:
  lxWeb:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: python_image
    container_name: python_box
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: nginx_image
    container_name: nginx_box
    volumes:
      - static:/apps/python/static
    ports:
      - "80:80"
      - "443:443"